package com.seleniumToolkit.selenium.pageObject;

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import java.util.List;

//PO generated by SeleniumToolkit-Extension
public class GetStarted extends AbstractSeleniumToolkitPageObject {

    public final String URL = "/get-started/";

    //Field declarations
    @FindBy(xpath="//*[@name='name']")
    public WebElement name;

    @FindBy(xpath="//*[@name='email']")
    public WebElement email;

    @FindBy(xpath="//*[@name='phone_number']")
    public WebElement phoneNumber;

    @FindBy(xpath="//*[@name='company']")
    public WebElement company;

    @FindBy(xpath="//*[@name='programmLangue_testFramework']")
    public WebElement programmLangueTestFramework;

    @FindBy(xpath="//*[@name='message']")
    public WebElement message;

    @FindBy(xpath="//*[@type='submit']")
    public WebElement submitButton;

    @FindBy(xpath = "//*[contains(@class, 'error') and .//input]")
    public List<WebElement> errorFields;

    //HelperMethods
    public void enterName(CharSequence input){
        enterRepalace( name, input);
    }

    public String getValueOfName(){
        return getValueOfInput(name);
    }

    public void enterEmail(CharSequence input){
        enterRepalace( email, input);
    }

    public String getValueOfEmail(){
        return getValueOfInput(email);
    }

    public void enterPhoneNumber(CharSequence input){
        enterRepalace( phoneNumber, input);
    }

    public String getValueOfPhoneNumber(){
        return getValueOfInput(phoneNumber);
    }

    public void enterCompany(CharSequence input){
        enterRepalace( company, input);
    }

    public String getValueOfCompany(){
        return getValueOfInput(company);
    }

    public void enterProgrammLangueTestFramework(CharSequence input){
        enterRepalace( programmLangueTestFramework, input);
    }

    public String getValueOfProgrammLangueTestFramework(){
        return getValueOfInput(programmLangueTestFramework);
    }

    public void enterMessage(CharSequence input){
        enterRepalace( message, input);
    }

    public String getValueOfMessage(){
        return getValueOfInput(message);
    }

    public void clickSubmitButton(){
        click( submitButton);
    }

    public int getErrorFieldSize(){
        return errorFields.size();
    }



}