package com.seleniumToolkit.selenium.pageObject;


import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

//PO generated by SeleniumToolkit-Extension
public class Home extends AbstractSeleniumToolkitPageObject {

    public final String URL = "/";

    //Field declarations
    @FindBy(xpath="//*[contains(@class,'button-1')]")
    public WebElement solutionButton;

    @FindBy(xpath="//a[.//*[contains(text(),'GET STARTED')]]")
    public WebElement getStartedButton;


    //HelperMethods
    public Solution clickSolutionButton(){
        click( solutionButton);
        return new Solution();
    }

    public GetStarted clickGetStartedButton(){
        click( getStartedButton);
        return new GetStarted();
    }



}