package com.seleniumToolkit.selenium.pageObject;

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

//PO generated by SeleniumToolkit-Extension
public class SeleniumHelp extends AbstractSeleniumToolkitPageObject{

    public final String URL = "/selenium-help/";

    //Field declarations
    @FindBy(xpath="//*[@aria-controls='tab-BrokenImages']")
    public WebElement tabBrokenImages;

    @FindBy(xpath="//*[@aria-controls='tab-ContextMenu']")
    public WebElement tabContextMenu;

    @FindBy(xpath="//*[@aria-controls='tab-DragDrop']")
    public WebElement tabDragDrop;

    @FindBy(xpath="//*[@aria-controls='tab-FileDownload']")
    public WebElement tabFileDownload;

    @FindBy(xpath="//*[@aria-controls='tab-Iframe']")
    public WebElement tabIframe;

    @FindBy(xpath="//*[@aria-controls='tab-JSAlert']")
    public WebElement tabJSAlert;

    @FindBy(xpath="//*[@aria-controls='tab-JsLogin_BasicAuthPopUp']")
    public WebElement tabJsLogin_BasicAuthPopUp;

    @FindBy(xpath="//*[@aria-controls='tab-NewWindow']")
    public WebElement tabNewWindow;

    @FindBy(xpath="//*[@aria-controls='tab-Hover']")
    public WebElement tabHover;

    @FindBy(xpath="//*[@aria-controls='tab-PageObjects']")
    public WebElement tabPageObjects;

    @FindBy(xpath="//*[@aria-controls='tab-Selectors']")
    public WebElement tabSelectors;

    @FindBy(xpath="//*[@aria-controls='tab-ShadowDOM']")
    public WebElement tabShadowDOM;

    @FindBy(xpath="//*[@aria-controls='tab-Table']")
    public WebElement tabTable;

    @FindBy(xpath="//*[@aria-controls='tab-Waits']")
    public WebElement tabWaits;


    //HelperMethods
    public void clickTabBrokenImages(){
        click( tabBrokenImages);
    }

    public void clickTabContextMenu(){
        click( tabContextMenu);
    }

    public void clickTabDragDrop(){
        click( tabDragDrop);
    }

    public void clickTabFileDownload(){
        click( tabFileDownload);
    }

    public void clickTabIframe(){
        click( tabIframe);
    }

    public void clickTabJSAlert(){
        click( tabJSAlert);
    }

    public void clickTabJsLogin_BasicAuthPopUp(){
        click( tabJsLogin_BasicAuthPopUp);
    }

    public void clickTabNewWindow(){
        click( tabNewWindow);
    }

    public void clickTabHover(){
        click( tabHover);
    }

    public void clickTabPageObjects(){
        click( tabPageObjects);
    }

    public void clickTabSelectors(){
        click( tabSelectors);
    }

    public void clickTabShadowDOM(){
        click( tabShadowDOM);
    }

    public void clickTabTable(){
        click( tabTable);
    }

    public void clickTabWaits(){
        click( tabWaits);
    }



}