package com.seleniumToolkit.selenium.pageObject;

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

//PO generated by SeleniumToolkit-Extension
public class Showcase extends AbstractSeleniumToolkitPageObject {

    public final String URL = "/showcase/";

    //Field declarations
    @FindBy(xpath="//*[@aria-controls='tab-Configuration']")
    public WebElement tabConfiguration;

    @FindBy(xpath="//*[@aria-controls='tab-CreateTestMethod']")
    public WebElement tabCreateTestMethod;

    @FindBy(xpath="//*[@aria-controls='tab-TestData']")
    public WebElement tabTestData;

    @FindBy(xpath="//*[@aria-controls='tab-GetWebdriver']")
    public WebElement tabGetWebdriver;

    @FindBy(xpath="//*[@aria-controls='tab-TakeScreenshots']")
    public WebElement tabTakeScreenshots;

    @FindBy(xpath="//*[@aria-controls='tab-AddExtraReportSteps']")
    public WebElement tabAddExtraReportSteps;

    @FindBy(xpath="//*[@aria-controls='tab-GenerateReport']")
    public WebElement tabGenerateReport;

    @FindBy(xpath="//*[@aria-controls='tab-NeoloadBridge']")
    public WebElement tabNeoloadBridge;


    //HelperMethods
    public void clickTabConfiguration(){
        click( tabConfiguration);
    }

    public void clickTabCreateTestMethod(){
        click( tabCreateTestMethod);
    }

    public void clickTabTestData(){
        click( tabTestData);
    }

    public void clickTabGetWebdriver(){
        click( tabGetWebdriver);
    }

    public void clickTabTakeScreenshots(){
        click( tabTakeScreenshots);
    }

    public void clickTabAddExtraReportSteps(){
        click( tabAddExtraReportSteps);
    }

    public void clickTabGenerateReport(){
        click( tabGenerateReport);
    }

    public void clickTabNeoloadBridge(){
        click( tabNeoloadBridge);
    }



}
