package com.seleniumToolkit.selenium.pageObject;


import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject;

//PO generated by SeleniumToolkit-Extension
public class Solution extends AbstractSeleniumToolkitPageObject {

    public final String URL = "/solutions/";
}